SELECT WORKER_TITLE,FIRST_NAME,LAST_NAME,DEPARTMENT
FROM TITLE T,WORKER_DETAILS W
WHERE T.WORKER_REF_ID=W.WORKER_ID
AND WORKER_TITLE='CONSULTANT';

WITH HIGHEST AS (
    SELECT DEPARTMENT,
	FIRST_NAME , 
	SALARY,
    DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RowNum
        FROM Worker_Details
)
SELECT DEPARTMENT, FIRST_NAME, SALARY
    FROM HIGHEST
    WHERE RowNum = 1;