CREATE TABLE PETINFORMATION1
(PETNAME VARCHAR(13) NOT NULL,
PETTYPE VARCHAR(14) NOT NULL,
PETID INT NOT NULL ,
PETAGE INT NOT NULL,
PETOWNER VARCHAR(14) NOT NULL,
VISITDATE DATE NOT NULL,
PROCESS VARCHAR(20) NOT NULL);