ALTER TABLE PETINFORMATION1
ADD CONSTRAINT PETNAME_PRIMARY_KEY
PRIMARY KEY (PETNAME);




ALTER TABLE PETINFORMATION1
ADD CONSTRAINT PETINFORMATION1_PETNAME_FK
FOREIGN KEY (PETNAME)
REFERENCES PETINFORMATION1(PETNAME);