CREATE TABLE PETINF (
 PETID                 int NOT NULL,
 PETNAME               VARCHAR(14),
 PETTYPE               VARCHAR(13),
 PETAGE                 int NOT NULL,
PETOWNER		VARCHAR(14),
CONSTRAINT PETINF_PRIMARY_KEY PRIMARY KEY (PETID));

INSERT INTO PETINF VALUES (1,'DOG','MALE',13,'BOOSTER');
INSERT INTO PETINF VALUES (2,'RABBIT','MALE',16,'VIPER');
INSERT INTO PETINF VALUES (3,'CAT','FEMALE',17,'DEMON');
INSERT INTO PETINF VALUES (4,'SANKE','MALE',31,'DEVIL');
INSERT INTO PETINF VALUES (5,'RAT','MALE',18,'SPYDER');
INSERT INTO PETINF VALUES (6,'TIGER','MALE',12,'TRIGGER');